{{- if and .Values.nats.enabled .Values.nats.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "project.fullname" . }}-nats
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "project.fullname" . }}-nats
  minReplicas: {{ .Values.nats.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.nats.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.nats.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.nats.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.nats.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.nats.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
