{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "project.fullname" . }}-nginx
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "project.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
{{- end }}
