# Default values for base-nginx.
# This is a YAML-formatted file.
# Override these values per application deployment.

replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""  # defaults to appVersion from Chart.yaml

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  fsGroup: 101

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Config map for custom nginx configuration
configMap:
  enabled: false
  data: {}
    # nginx.conf: |
    #   # Custom nginx config

# Additional volumes
volumes: []
# - name: cache
#   emptyDir: {}
# - name: config
#   configMap:
#     name: nginx-config

# Additional volumeMounts
volumeMounts: []
# - name: cache
#   mountPath: /var/cache/nginx
# - name: config
#   mountPath: /etc/nginx/nginx.conf
#   subPath: nginx.conf

# Nginx cache directories (required for read-only filesystem)
# These are automatically added when securityContext.readOnlyRootFilesystem is true
nginxCacheVolumes:
  enabled: true
  mounts:
    - name: nginx-cache
      mountPath: /var/cache/nginx
    - name: nginx-run
      mountPath: /var/run

nodeSelector: {}

tolerations: []

affinity: {}
  # podAntiAffinity:
  #   preferredDuringSchedulingIgnoredDuringExecution:
  #   - weight: 100
  #     podAffinityTerm:
  #       labelSelector:
  #         matchExpressions:
  #         - key: app.kubernetes.io/name
  #           operator: In
  #           values:
  #           - base-nginx
  #       topologyKey: kubernetes.io/hostname
