apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services-app-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - service: api-service
                  locale: br
                - service: api-service
                  locale: ph
                - service: docs-site
          - list:
              elements:
                - environment: production
                - environment: staging
  template:
    metadata:
      name: "{{ .service }}{{ if .locale }}-{{ .locale }}{{ end }}-{{ .environment }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default

      source:
        repoURL: https://github.com/pk-hash/test2.git
        targetRevision: HEAD
        path: charts/project
        helm:
          parameters:
            - name: locale
              value: "{{ .locale }}"
          valueFiles:
            - "../../examples/{{ .environment }}/{{ .service }}.yaml"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .environment }}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

      revisionHistoryLimit: 10
